kind = "web"
previewPath = "/"
title = "Simran OS"
version = "1.0.0"
id = "artifacts/simran-os"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25208

[services.development]
run = "pnpm --filter @workspace/simran-os run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/simran-os", "run", "build" ]
publicDir = "artifacts/simran-os/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25208"
BASE_PATH = "/"
